descriptor_extension: yml
package:
  description: Ejemplo que muestra dos contenedores con scapy conectados en serie
  maintainer: homero, CompuMundoHipermegaRed, homero@compumundohipermegared.com
  name: scapy2-service
  vendor: eu.sonata-nfv.package
  version: '0.1'
version: '0.5'
