# TIENE ERRORES

# Global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s

# A scrape configuration for cadvisor
scrape_configs:
  # cadvisor
  - job_name: 'cadvisor'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['172.21.38.5:8090'] 

  - job_name: 'docker'
    static_configs:
      - targets: ['172.21.38.5:9323'] 

  - job_name: 'ovs'
    static_configs:
      - targets: ['172.21.38.5:9177'] 
      
#  - job_name: 'ports'
#    static_configs:
#      - targets: ['172.21.38.5:8081']
#    metrics_path: /ports
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: 127.0.0.1:8081  # OVS exporter.

#  - job_name: 'flows'
#    static_configs:
#      - targets: ['172.21.38.5:8081']
#    metrics_path: /flows
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: 127.0.0.1:8081  # OVS exporter.