version: '2'


services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # get the prometheus config file
    volumes:
     - ./prometheus:/etc/prometheus
    # - ./prometheus/data:/prometheus/data
    ports:
     - 9090:9090
    command: [--config.file=/etc/prometheus/prometheus_sdk.yml]

  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana
    ports:
      - 3000:3000
    user: "104"
    links:
      - prometheus
  
  cadvisor:
   image: google/cadvisor:canary
   container_name: cadvisor
   volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
   ports:
    - "8090:8080"
